kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: candi-tails-server
  annotations:
    description: aries agent connect to BCovrin test ledger
    tags: experimentation, aries, sovrin, issuer, verifier
objects:
#
# aries cloud agent
#
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: candi-tails-server
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: candi-tails-server
    name: candi-tails-server
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'candi-tails-server:latest'
    resources: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: docker/Dockerfile.tails-server
    postCommit: {}
    source:
      contextDir: .
      type: Git
      git:
        uri: 'https://github.com/bcgov/indy-tails-server.git'
    triggers:
      - type: ConfigChange
    runPolicy: Serial
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: candi-tails-server
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: candi-tails-server
    labels:
      app: candi-tails-server
      app.kubernetes.io/part-of: MultiTenant
  spec:
    strategy:
      type: Recreate
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - candi-tails-server
          from:
            kind: ImageStreamTag
            name: 'candi-tails-server:latest'
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: candi-tails-server
    template:
      metadata:
        labels:
          app: candi-tails-server
      spec:
        containers:
          - name: candi-tails-server
            command:
              - bash
              - -c
              - $(echo tails-server
                --host '0.0.0.0' 
                --port ${TAILS_SERVER_PORT}
                --storage-path ${TAILS_STORAGE_PATH}
                --log-level ${LOG_LEVEL});
            image: " "
            ports:
              - containerPort: 6543
                protocol: TCP
            readinessProbe:
              timeoutSeconds: 30
              initialDelaySeconds: 3
              exec:
                command:
                  - bash
                  - "-c"
                  - 'curl --fail "http://localhost:${TAILS_SERVER_PORT}/match/12345"'
            livenessProbe:
              timeoutSeconds: 30
              initialDelaySeconds: 300
              exec:
                command:
                  - bash
                  - "-c"
                  - 'curl --fail "http://localhost:${TAILS_SERVER_PORT}/match/12345"'
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
            volumeMounts:
            - name: candi-tails-storage
              mountPath: "${TAILS_STORAGE_PATH}"
        volumes:
        - name: candi-tails-storage
          persistentVolumeClaim:
            claimName: candi-tails-server
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: candi-tails-server
  spec:
    selector:
      app: candi-tails-server
    ports:
      - name: '6543'
        protocol: TCP
        port: 6543
        targetPort: 6543
- kind: Route
  apiVersion: v1
  metadata:
    name: candi-tails-server
  spec:
    host: candi-tails-server.apps.ocp1.az.uat.aro.gocloud.gov.on.ca
    to:
      kind: Service
      name: candi-tails-server
      weight: 100
    tls:
      termination: edge
    port:
      targetPort: 6543
    wildcardPolicy: None
#
# parameters
#
parameters:
- name: LOG_LEVEL
  displayName: Log Level
  description: The logging level of the agent.
  required: true
  value: DEBUG
- name: TAILS_STORAGE_PATH
  displayName: Tails files storage path
  required: true
  description: The path where tails files are stored
  value: "/tmp/tails-files"
- name: TAILS_SERVER_PORT
  displayName: Tails server port
  description: The port on which the service will listen.
  required: true
  value: "6543"
